# Generated by Django 2.2.3 on 2019-07-29 20:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=30, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=70)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('description', models.TextField(null=True)),
                ('main_color', models.CharField(max_length=30)),
                ('style', models.CharField(choices=[('casual', 'Casual'), ('formal', 'Social')], default='casual', max_length=10)),
                ('size', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(65), django.core.validators.MinValueValidator(1)])),
                ('external_material', models.CharField(max_length=30, null=True)),
                ('internal_material', models.CharField(max_length=30, null=True)),
                ('sole_material', models.CharField(max_length=30, null=True)),
                ('weight', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=8)),
                ('height', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=8)),
                ('width', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=8)),
                ('length', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('express_shipping', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'shoes',
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=128)),
                ('ordering', models.IntegerField(default=0)),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shoes.Shoes')),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
    ]
